# Generated by Django 4.0.6 on 2022-07-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_update',
            field=models.DateField(editable=False, null=True),
        ),
    ]
