# Generated by Django 4.0.6 on 2022-07-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_post_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='static/image/nopic.png', upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_update',
            field=models.DateField(null=True),
        ),
    ]
