# Generated by Django 4.0.6 on 2022-07-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_post_cover_image_alter_post_date_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
    ]
