# Generated by Django 4.0.6 on 2022-07-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
