# Generated by Django 4.0.6 on 2022-07-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('test', 'test')], max_length=50),
        ),
    ]
