# Generated by Django 4.0.6 on 2022-07-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
