# Generated by Django 4.0.6 on 2022-07-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_description', models.TextField(max_length=150)),
                ('site_domain', models.CharField(max_length=100)),
                ('site_paginate', models.IntegerField(default=5)),
                ('site_about', models.TextField(max_length=150)),
                ('site_author', models.CharField(default='salman', max_length=50)),
            ],
        ),
    ]
