# Generated by Django 4.0.6 on 2022-07-13 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('test', 'test'), ('tesstingg', 'tesstingg')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_author',
            field=models.CharField(default='salman', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_paginate',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
