# Generated by Django 4.0.6 on 2022-07-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_post_tag_alter_sitesettings_site_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('fdfdfdf', 'fdfdfdf'), ('jhjhkjh', 'jhjhkjh'), ('tefdsfsf', 'tefdsfsf'), ('tesstingg', 'tesstingg'), ('test', 'test')], max_length=50),
        ),
    ]
