# Generated by Django 4.0.6 on 2022-07-17 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_rename_user_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
