# Generated by Django 4.0.6 on 2022-07-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_remove_post_author_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
