# Generated by Django 4.0.6 on 2022-07-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_rename_user_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
