# Generated by Django 4.0.6 on 2022-07-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
